services:
  - type: web
    name: agendaai
    runtime: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      python manage.py migrate
      gunicorn AgendaAI.wsgi:application --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.3"
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "localhost,127.0.0.1,*.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://*.onrender.com"
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: SECURE_PROXY_SSL_HEADER
        value: "HTTP_X_FORWARDED_PROTO,https"
      - key: DATABASE_URL
        fromDatabase:
          name: agendaai-db
          property: connectionString

 databases:
   - name: agendaai-db
     databaseName: agendaai
     user: agendaai
