# Generated by Django 6.1.1 on 2026-09-22 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_professional_active_service_active_availability_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['day_of_week', 'start_time']},
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='accounts_ap_start_t_04f88b_idx',
            old_name='accounts_ap_start_t_5a0b3a_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='accounts_ap_custome_addfd8_idx',
            old_name='accounts_ap_customer_7b1f77_idx',
        ),
    ]
